---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-namespace-reader
  namespace: sa-rbac
subjects:
  - kind: ServiceAccount
    name: openshift-tools
    namespace: sa-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
