---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-cluster-admin
  namespace: sa-rbac
subjects:
  - kind: ServiceAccount
    name: openshift-tools
    namespace: sa-rbac
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
