---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'mysql'
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: registry.redhat.io/rhel8/mysql-80:1
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database
            - name: MYSQL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: hostname
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: user
          volumeMounts:
            - name: mysql-volume
              mountPath: /run/secrets/mysql
      volumes:
        - name: mysql-volume
          secret:
            secretName: mysql
            defaultMode: 420
