---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: busybox
          command:
            - sh
            - -c
            - echo "scale=10000; 4*a(1)" | bc -l
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits: 
              cpu: 50m
              memory: 20Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false
